### ISSUE TITLE
API endpoint /sites/{siteId}/prices is returning 502 when the endDate is > 2022-06-30

### ISSUE THREAD

**Issue by GrahamLea** [amberelectric/public-api#116]
Description says it all?

**Comment by madpilot** [comment]
Should be fixed COB

**Comment by ps-jay** [comment]
Hahah. I ❤️ EOFY impacts on IT systems. So random. 

Keep up the good work @madpilot 
I'm sticking with Amber through these crazy times as a vote of how good the openness of the API is, and your community involvement
