### ISSUE TITLE
demandWindow is always False

### ISSUE THREAD

**Issue by herbi3** [amberelectric/public-api#141]
Gidday, when grabbing the pricing for the day, the demandWindow is always false. I know our demand window with Energex is between 4pm and 9pm, is the demand window via the api available?

```
async def get_amber_data(session, type):
	try:
		if type == "current":
			url = f"https://api.amber.com.au/v1/sites/{SITE_ID}/prices/current"
		if type == "forecast":
			today = datetime.today().strftime("%Y-%m-%d")
			url = f"https://api.amber.com.au/v1/sites/{SITE_ID}/prices?endDate={today}&resolution=5"
		async with session.get(url, headers=AMBER_HEADERS, timeout=2) as response:
			response.raise_for_status()
			if response.status != 200:
				print("Error getting Amber Data")
			else:
				json_data = await response.json()
				return json_data
	except aiohttp.ClientError as e:
		print(f"Amber data error occurred: {e}")
		await health_check(session, HEALTHCHECKS_IO_URL+"/log", f"Amber data error occurred: {e}")
	except asyncio.exceptions.TimeoutError as e:
		print(f"Amber data time out")
		await health_check(session, HEALTHCHECKS_IO_URL+"/log", f"Amber data time out")
	except Exception as e:
		print(f"Amber data error occurred: {e}")
```

returns

`{"type": "ActualInterval", "date": "2023-05-04", "duration": 5, "startTime": "2023-05-03T14:30:01Z", "endTime": "2023-05-03T14:35:00Z", "nemTime": "2023-05-04T00:35:00+10:00", "perKwh": 31.4504, "renewables": 4.078274498870494, "spotPerKwh": 21.11469, "channelType": "general", "spikeStatus": "none", "tariffInformation": {"demandWindow": False}, "descriptor": "low"},`

**Comment by madpilot** [comment]
What tariff are you on?

**Comment by herbi3** [comment]
General is 3950
FiT is 9850

I am on the demand tariff instead of the time of use

```
    "channels": [
      {
        "identifier": "E1",
        "type": "general",
        "tariff": "3950"
      },
      {
        "identifier": "B1",
        "type": "feedIn",
        "tariff": "9850"
      }
    ],
    "network": "Energex",
    "status": "active",
    "activeFrom": "2023-01-27"
  }
]
```

**Comment by madpilot** [comment]
Looks like a bug in our tariff definitions. I'll get it sorted for you.

**Comment by madpilot** [comment]
Should be fixed now!

**Comment by herbi3** [comment]
Perfect! Great stuff @madpilot !

![image](https://user-images.githubusercontent.com/11141749/237045891-fc6a211c-c1e1-46d7-a89c-d8c17a23c5cd.png)
