### ISSUE TITLE
demandWindow is always true

### ISSUE THREAD

**Issue by upsuper** [amberelectric/public-api#161]
It seems to be opposite to #141.

In the schema, for `tariffInformation.demandWindow` it says
> Is this interval currently in the demand window? Only available if the site in on a demand tariff

I'm currently on tariff EA116 of Ausgrid. Based on Ausgrid's [Tariff Structure Statement](https://cdn.ausgrid.com.au/-/media/Documents/Regulation/Reports-plans/Ausgrid-approved-TSS-2019-24.pdf?rev=bdcad85222e34653a4e1df2177a433cf):
![image](https://github.com/amberelectric/public-api/assets/333750/80ff991e-2eb8-4e0e-a832-90017c6e8357)

However, in the data I fetch from the public API, basically every interval says `demandWindow: true`, for example:
```json
  {
    "type": "ActualInterval",
    "date": "2023-09-11",
    "duration": 30,
    "startTime": "2023-09-10T15:30:01Z",
    "endTime": "2023-09-10T16:00:00Z",
    "nemTime": "2023-09-11T02:00:00+10:00",
    "perKwh": 15.88945,
    "renewables": 8.764,
    "spotPerKwh": 8.39249,
    "channelType": "general",
    "spikeStatus": "none",
    "tariffInformation": {
      "demandWindow": true
    },
    "descriptor": "veryLow"
  },
```
and
```json
  {
    "type": "ForecastInterval",
    "date": "2023-09-13",
    "duration": 30,
    "startTime": "2023-09-12T16:30:01Z",
    "endTime": "2023-09-12T17:00:00Z",
    "nemTime": "2023-09-13T03:00:00+10:00",
    "perKwh": 17.44116,
    "renewables": 4.5828204631863905,
    "spotPerKwh": 9.8472,
    "channelType": "general",
    "spikeStatus": "none",
    "tariffInformation": {
      "demandWindow": true
    },
    "descriptor": "veryLow"
  },
```

The value is clearly wrong I believe.

(I initially posted it as a [discussion](https://github.com/amberelectric/public-api/discussions/157), and it seems @sstteevvee there has the same problem.)

**Comment by herbi3** [comment]
The data retrieved shows 2pm on the 11th of September, which for that tariff the demand window starts at 2pm until 8pm based on the tariff information, so the data retrieved is true?

Can you show more data say for 10am and see if it's the same?

**Comment by upsuper** [comment]
`2023-09-11T02:00:00+10:00` means 2am I believe. 2pm should be 14:00.

**Comment by sstteevvee** [comment]
As upsuper mentioned, I'm also having the same problem on the EA116 tariff.

The attached [AlwaysDemandEA116.zip](https://github.com/amberelectric/public-api/files/12826366/AlwaysDemandEA116.zip) contains examples of the JSON data I receive. It includes my `sites` (id and nmi obscured), and output from `prices`, `prices_current`, and `usage` requests.

In a full day of data (both past and future) there are 48 "is demand" blocks, so its not even just missing when its not demand.

**Comment by madpilot** [comment]
We'll be reviewing all deman tariff soon, which should clean up all of these issues.

**Comment by upsuper** [comment]
This seems to have been solved. The latest data I fetched has the correct demand window information now.
