### ISSUE TITLE
current prices not showing feed in channel

### ISSUE THREAD

**Issue by machship-mm** [amberelectric/public-api#168]
When I hit the `sites/{siteId}/prices/current` endpoint, I am only being provided with the `"channelType": "general"` result for the `"CurrentInternal"`, and am not being given the other intervals, not the "feed in" channel.

Endpoint:
```
https://api.amber.com.au/v1/sites/01HF6CERC8M9J1YX04SY2MFBQ3/prices/current
```

Result from API:
```
[
    {
        "type": "CurrentInterval",
        "date": "2023-11-15",
        "duration": 30,
        "startTime": "2023-11-15T09:30:01Z",
        "endTime": "2023-11-15T10:00:00Z",
        "nemTime": "2023-11-15T20:00:00+10:00",
        "perKwh": 40.12465,
        "renewables": 20.244,
        "spotPerKwh": 23.69888,
        "channelType": "general",
        "spikeStatus": "none",
        "descriptor": "low",
        "estimate": true
    }
]
```

**Comment by madpilot** [comment]
Your site doesn't have an export channel, so we can't show a feed in price. 

Have you recently had your Powerwall installed? It's possible the installer hasn't submitted the paperwork yet, or we are still waiting on the network to enable your export channel. I'd check with your installer first.

If you've had your battery for a while, email in to info@amber.com.au - the metering team can help you get the application sorted out.

**Comment by machship-mm** [comment]
Thanks, I have signed up for export, it just hasn't been completed yet. 

I can see the export prices in the iOS app, so I would appreciate it if you could add the feed-in prices so that I can prepare my integrations in lieu of the feed-in tariff becoming live.

**Comment by madpilot** [comment]
The app and the API come from the same place so if you have it in one, it'll be in the other.

The one exception: if you turn in the "show feed in price" option in the settings. That doesn't affect the API.

**Comment by machship-mm** [comment]
Cheers @madpilot, I've sent a support ticket.
