### ISSUE TITLE
OpenAPI Spec - Representing Minute values as integers instead of floating point numbers.

### ISSUE THREAD

**Issue by CarlLusty** [amberelectric/public-api#173]
Hello,

In the Amber Spec document, you have two types that appear to represent Minutes:
- duration
- resolution

Both are defined as closed enums with values such as 5, 15, 30 etc.
Minor side-note, 'duration' explicitly states in the description fields that it is minutes, but 'resolution' does not. 

All duration and resolution fields are defined as 'number' (floating point) enums. Would it make more sense to change these to 'integer' enums?

Per https://github.com/OAI/OpenAPI-Specification/blob/main/versions/3.0.0.md, OpenAPI 3.0.0 supports the 'integer' type.
In the Amber Spec, the existing specified values for these types are already integers, so it shouldn't break them.
Most statically typed languages provide much better support for integer enums than floating point enums, if they support floating point enums at all.

Opinion?

Thanks,
Carl.

**Comment by madpilot** [comment]
Sounds reasonable. I'll have a look

**Comment by madpilot** [comment]
I've made the requested changes and added a copy of the swagger.json file to this repo, so you can test before I publish to the main repo. This will also allow PRs. 

https://github.com/amberelectric/public-api/blob/main/swagger.json

**Comment by CarlLusty** [comment]
In line with this issue.

- Should TariffInformation.block (min 1, max 2) be an integer? (currently a number)
- Same question for Interval.renewables which appears to be a percentage. More than reasonable to keep it this way, if you ever return a floating point number here.
- Same with Renewable.renewables. 

Interval.renewables and Renewable.renewables could also be combined into a Type, say RenewablesPercentage.
