### ISSUE TITLE
Only 47 reading per day

### ISSUE THREAD

**Issue by rob0101** [amberelectric/public-api#18]
If I request usage for a specific day, I only get 47 x 30m blocks.

The first is timestamped
"nemTime" : "2021-06-17T00:30:00+10:00",

The last is
"nemTime" : "2021-06-17T23:30:00+10:00",

The midnight reading is missing.

**Comment by madpilot** [comment]
Good pick up - I'll get that sorted out ASAP

**Comment by madpilot** [comment]
Fixed!
