### ISSUE TITLE
All Operation Object's are missing operationId fields

### ISSUE THREAD

**Issue by CarlLusty** [amberelectric/public-api#190]
The operationId field is used by generators to make sensible API interface methods.

OpenAPI 3.0.0 description of the operationId field:
 - Unique string used to identify the operation. The id MUST be unique among all operations described in the API. Tools and libraries MAY use the operationId to uniquely identify an operation, therefore, it is RECOMMENDED to follow common programming naming conventions.

Here are some example function signatures using "/state/{state}/renewables/current" and Apples official OpenAPI generator:
 - Without operationId: 
```swift
func get_sol_state_sol__lcub_state_rcub__sol_renewables_sol_current(_ input: Operations.get_sol_state_sol__lcub_state_rcub__sol_renewables_sol_current.Input) async throws -> Operations.get_sol_state_sol__lcub_state_rcub__sol_renewables_sol_current.Output
```
 - With "operationId": "getCurrentRenewablesForState": 
```swift
func getCurrentRenewablesForState(_ input: Operations.getCurrentRenewablesForState.Input) async throws -> Operations.getCurrentRenewablesForState.Output
```

Adding operationId values seems like a great feature to add for API users.

My suggestions:
- getCurrentRenewablesForState
- getAllSites
- getPricesForSite
- getCurrentPricesForSite
- getUsageForSite

Opinion?

Carl.

**Comment by madpilot** [comment]
Got an internal PR for this already. Waiting for approval. Should be up tomorrow.

**Comment by madpilot** [comment]
Done
