### ISSUE TITLE
Is ForecastInterval.range relative to ForecastInterval.perKwh or ForecastInterval.spotPerKwh ?

### ISSUE THREAD

**Issue by CarlLusty** [amberelectric/public-api#193]
I have noticed instances of ForecastInterval where ForecastInterval.perKwh is outside of ForecastInterval.range (when reported).
For reference, I've included an example below.

The easy answer may be that I have assumed wrong and ForecastInterval.range refers to the potential value of ForecastInterval.spotPerKwh and not ForecastInterval.perKwh.

I checked the documentation but it isn't all that clear to me which it is.
Docs:
 - ForecastInterval.range: When prices are particularly volatile, the API may return a range of prices that are possible.
 - ForecastInterval.range.min: Estimated minimum price (c/kWh)
 - ForecastInterval.range.max: Estimated maximum price (c/kWh)

Is ForecastInterval.range relative to ForecastInterval.perKwh or ForecastInterval.spotPerKwh?

Thanks,
Carl.

```
{
   "channelType" : "general",
   "date" : "2024-03-01",
   "descriptor" : "low",
   "duration" : 30,
   "endTime" : "2024-02-29T21:00:00Z",
   "nemTime" : "2024-03-01T07:00:00+10:00",
   "perKwh" : 39.39479,
   "range" : {
      "max" : 33.1361,
      "min" : 12.80394
   },
   "renewables" : 20.1793485907705,
   "spikeStatus" : "none",
   "spotPerKwh" : 29.53254,
   "startTime" : "2024-02-29T20:30:01Z",
   "tariffInformation" : {
      "demandWindow" : false
   },
   "type" : "ForecastInterval"
},
```

**Comment by madpilot** [comment]
It's relative to the spot price

**Comment by CarlLusty** [comment]
Thanks.
