### ISSUE TITLE
Advanced Price Forecast access via the AmberAPI

### ISSUE THREAD

**Issue by purcell-lab** [amberelectric/public-api#203]
The AmberAPI current supports range_min & range_max data for time intervals (sometimes #192). However this data has proven to not be very useful as they are generally to broad in their spread.

![324722949-2f4d4bb8-d037-4b7e-932c-571e081ac61c](https://github.com/amberelectric/public-api/assets/79175134/d142eb7f-e42a-4da2-87c8-b649dd5b4afd)

SmartShift now supports Advanced Price Forecasts which have a very sensible spread and can readily benefit users if the API is they were published.

![Screenshot_20240523-200234](https://github.com/amberelectric/public-api/assets/79175134/3da4acc7-778e-42a4-9ee6-bc25cb53fd3b)

It would be great if the current range_min/ max points could be updated to publish the Advanced Price Forecasts.

**Comment by madpilot** [comment]
I'm going to be looking at this shortly.

We'll be adding a new attribute, rather than reusing the existing one.

**Comment by JoshC1994** [comment]
Is it possible to get 5min granularity for this advanced forecast pricing? Just saving some work for when the 5min pricing intervals comes in to effect?

**Comment by madpilot** [comment]
It'll be what ever resolution that you request.

**Comment by purcell-lab** [comment]
Nice work team:
https://github.com/amberelectric/public-api/discussions/214
![Screenshot_20240705-205639](https://github.com/amberelectric/public-api/assets/79175134/5301fc91-9c5d-4ada-9552-4261ae5f3760)
