### ISSUE TITLE
5 minute forecasts don't align with transitional TOU periods 

### ISSUE THREAD

**Issue by purcell-lab** [amberelectric/public-api#212]
My ToU peak period starts at 1600.

The 30 minute intervals are tagged correctly via the API, however the 5 minute intervals are not tagged correctly and as a consequence the perkWh field is also calculated incorrectly.

I would appear that the last 5 minute interval of the initial 30 minute interval is tagged as peak, whilst I would suggest that all the 5 minute intervals should be tagged as peak and the associated perkWh field requires update.

![Screenshot-2024-07-01-16-04-42 (1)](https://github.com/amberelectric/public-api/assets/79175134/607143b5-100d-47ab-a3f4-72b847e72384)

![Screenshot_20240701-161614](https://github.com/amberelectric/public-api/assets/79175134/b3a5aeb4-e237-4ad9-a286-8437a3c5a2a9)

**Comment by madpilot** [comment]
Good pickup. Will have a look

**Comment by madpilot** [comment]
Fixed!
