### ISSUE TITLE
Changes to API key strcuture ?

### ISSUE THREAD

**Issue by craigcurtin-dev** [amberelectric/public-api#220]
Myles - i just cloned an existing production VM to enable me to do some testing.

Usually when i do this all my API keys (including Amber) all come across and work fine.

This time the AMber ones are failing to return data - i thought maybe it was an issue with the key being on two different machines - so i generated a new key and changed my api call on the new machine and i am geting a 403 expressly forbidden

Have there been any changes that could be causing this behaviour.

It is a straight clone of a VM (names and IPs changed) with no other changes 

I performed the same action just over a month ago to introduce the new version of Node Red into my production and the APIs all worked fine - not this time.

Craig

**Comment by madpilot** [comment]
No, nothing has changed - there is no limit to how mayn times a key is used.

what does the `/v1/sites` endpoint return?

**Comment by craigcurtin-dev** [comment]
Yep will run some more test and come back shortly- just wanted to make sure it was not something out of my control - thanks for the quick response



Sent on the go with Vodafone
Get Outlook for Android<https://aka.ms/AAb9ysg>
________________________________

**Comment by craigcurtin-dev** [comment]
I generated another key today and used that and it worked fine so something bizarre with how i cut and paste it from the generating screen - i checked my Password Manager where i store these and it has the same length etc so not sure what was happening there. THanks for looking

**Comment by craigcurtin-dev** [comment]
Closed - my fault apparently
