### ISSUE TITLE
API (5 min and 30 min) suddenly stopped working

### ISSUE THREAD

**Issue by craigcurtin-dev** [amberelectric/public-api#221]
Myles as of about 1:30PM today the API appears to have stopped returning results.

No changes at my end on the VM that runs the calls - think something has bitten the dust at your end ?

Craig

**Comment by craigcurtin-dev** [comment]
The calls are working OK and returning a 200 but no data is being returned. (EDIT) not true - only hsitorical (Actual Interval) data is being returned - no forecast data

(EDIT EDIT) - both the web browser and the Android App are having the same issue so i assume you are aware of it !


Craig

**Comment by ross-w** [comment]
@madpilot I'm seeing the same as @craigcurtin-dev, FYI. Jemena in VIC for me.

**Comment by madpilot** [comment]
AEMO is down. It's slowly coming back up now.

**Comment by craigcurtin-dev** [comment]
Sorry should have also said – Sydney – Ausgrid – but seems to be widespread based on FB

**Comment by craigcurtin-dev** [comment]
Geez – I wonder if that means free electricity for all ?

**Comment by craigcurtin-dev** [comment]
Yep seeing data flowing again

**Comment by madpilot** [comment]
The market is currently suspended, so it's likely prices will be retroactively revised at some point. They expect the market to be back trading at around 3:30pm GMT+10

**Comment by chiefcomm** [comment]
@madpilot is AEMO suspended again today - API data stopped flowing at approx 9:30am GMT+10.

**Comment by rcruikshank** [comment]
@madpilot Same here.  Stopped at 9:30ish.

**Comment by ffrog8** [comment]
And good news coincided with spike in SA!

**Comment by rob0101** [comment]
Really bad timing in SA.   We had a spike and stale prices were still in my Tesla TBC schedule when I expected it to sell.  Instead I used grid power.
