### ISSUE TITLE
Positive feedin and usage in same intervals

### ISSUE THREAD

**Issue by Mijawel** [amberelectric/public-api#223]
I'm seeing positive values for feedin and usage in the same intervals. I was wondering if Amber charges the net of those values or bills them separately? And does it make a difference if the property is 3 phase or not.

For example:
Total Price: 11c/kwh
Spot Price: 1c/kwh

Usage: 1 kWh
FeedIn: 1 kWh

Billed separately: 10c (1kwh x 11c - 1kwh x 1c)
Billed net: 0c (1kwh-1kwh)x 11c

**Comment by madpilot** [comment]
> And does it make a difference if the property is 3 phase or not.

No, we net meter, so we don't care what phase the power leaves and comes back on.

> Billed separately: 10c (1kwh x 11c - 1kwh x 1c)
> Billed net: 0c (1kwh-1kwh)x 11c

It'll be billed net, so in this case: 0c.

**Comment by rob0101** [comment]
> 
> It'll be billed net, so in this case: 0c.

If the imports and exports happen at the exact same time.

If you import 1kWh then export 1kWh during the same interval, you pay the 10c

**Comment by madpilot** [comment]
This is a good point. The prices from the API are _already_ net metered, so it'll be 11c

**Comment by Mijawel** [comment]
If they are already net metered, how are we getting positive values for both usage and exports in the same interval?

**Comment by madpilot** [comment]
Because an interval is thirty minutes long, and there will be instances of imports and exports through out that interval.

Net metering is across phases where it's possible to import and export at the same time. P1 exporting at 5kW and P2 importing at 2kW is a net export of 3kW.

**Comment by Mijawel** [comment]
Just a bit odd, as I set the battery to load follow at a level which matches the total output of all three phases, but I seem to still be seeing significant usage (1kwh+). I would expect to see some usage as load following isn't perfect, but not 1kwh worth. 

That's what lead me to ask the question in the first place.

Edit: I'll take a look through the data again and double check it. Maybe I'm wrong.

**Comment by madpilot** [comment]
What inverter?

**Comment by Mijawel** [comment]
It's a 5kW inverter (single phase) connected to a 10kWh battery. I have a separate Shelly meter on each phase to get the combined load every 10s, then command the battery to load follow that value.

I have looked at the data again. From 9-10pm yesterday the total usage was 0.151kWh (from the Amber API)

And the phases were as follows: (From the Shelly meters)
A 1.51 kWh
B 0.433 kWh
C -1.95 kWh
Total: -0.007 kWh

This is close enough to the Amber value that it looks like it's net metering as expected. The fact that it doesn't come out exactly as 0 probably shows what @rob0101 is talking about that if you don't match the load at the exact same time, you can get positive values on both exports and imports.

**Comment by madpilot** [comment]
I'm not an expert in metrology, but I'm not sure you can net meter _energy_ samples - you need to net meter the _power_ samples. Otherwise sampling rates, lengths and offsets will result in different values.

**Comment by Mijawel** [comment]
Yep, I've been trying to use power samples instead of energy samples. So far, I seem to be able to match about 95% of the load doing it that way. 

I'm not sure I can do much better than that without a 3 phase inverter that can measure and match the load in realtime (I'm dealing with 10-20 second delays, which means I'll lag behind any big changes in power).
