### ISSUE TITLE
/usage endpoint fails with an internal server error

### ISSUE THREAD

**Issue by mikemortimer** [amberelectric/public-api#26]
All other endpoints working well except the /usage - unless I'm using it incorrectly

**Comment by madpilot** [comment]
How are you using it?

**Comment by mikemortimer** [comment]
was just hitting it like all the other endpoints, authenticated GET request using startDate and endDate parameters along with my siteID in then request URL

**Comment by madpilot** [comment]
Can you give me an example request? Just the site id and query params will be fine

**Comment by mikemortimer** [comment]
https://api.amber.com.au/v1/sites/01EEATYEG8B3N6TMR2T95NJ7A9/usage?startDate=2021-01-01&endDate=2021-06-22

**Comment by mikemortimer** [comment]
Returns a 502 error

**Comment by madpilot** [comment]
It'll be a timeout - that's quite a large query. I'll
Check the logs when I'm back

**Comment by mikemortimer** [comment]
oh, wow, yeah I see the usage data coming back now over a smaller 7 day window - I should have expected it would be in 30 min blocks - yes, that's a lot of data!

**Comment by mikemortimer** [comment]
Might be worth thinking about pagination on this endpoint to allow incremental exports of full usage data

**Comment by madpilot** [comment]
You just change the start and end date. The results will be continuous.

**Comment by mikemortimer** [comment]
What's the guidance on maximum window to query for?

**Comment by madpilot** [comment]
90 days is probably a good range. I have a card to implement that server side

**Comment by mikemortimer** [comment]
Awesome, thanks 👍
