### ISSUE TITLE
API Key does not revoke/delete from the API explorer

### ISSUE THREAD

**Issue by DanubeRS** [amberelectric/public-api#6]
Tried out the swagger as soon as I could with a quick little test key. Unfortunately, revoking a key does not seem to work (it remains listed) and still looks to remain working against the API.

**Comment by madpilot** [comment]
The delete button has a confirm step - did you click it twice?

**Comment by madpilot** [comment]
Actually, I am seeing that in prod now. Thanks for the bug report

**Comment by craigcurtin-dev** [comment]
I think this is still there ? I created a key - used it today, posted on a public forum for some help, then promptly deleted it and generated a new one - but the new one looks like the old one still (in fact is the old one ?)

i.e. my key is out in the wild at the moment

Craig

**Comment by madpilot** [comment]
Correct - I haven't fixed the issue yet

**Comment by madpilot** [comment]
It's now fixed.
