### ISSUE TITLE
The date field could do with a timezone clarification

### ISSUE THREAD

**Issue by GrahamLea** [amberelectric/public-api#68]
Documentation on `nemTime`, `startTime` and `endTime` are very clear that they're in UTC+10, UTC and UTC, respectively.

However, the `date` field (on `Usage`, at least) doesn't say what timezone it's referring to, which is important, even though it doesn't have a time component. I'm guessing it's also UTC+10 based on the reference to `nemTime` in the description, but it'd just be good to have it explicitly stated. 🙏

**Comment by GrahamLea** [comment]
Opening the can of worms: Would it make sense for it to use the site's timezone (or for there to be another field that provides that)? 😬

**Comment by madpilot** [comment]
> Documentation on `nemTime`, `startTime` and `endTime` are very clear that they're in UTC+10, UTC and UTC, respectively.
> 
> 
> 
> However, the `date` field (on `Usage`, at least) doesn't say what timezone it's referring to, which is important, even though it doesn't have a time component. I'm guessing it's also UTC+10 based on the reference to `nemTime` in the description, but it'd just be good to have it explicitly stated. 🙏

Yep, it's NEM time. All add docs on Monday

**Comment by madpilot** [comment]
> Opening the can of worms: Would it make sense for it to use the site's timezone (or for there to be another field that provides that)? 😬

No, we made an explicit design decision to use UTC. Clients then only have to do one conversion if they want the times in a different time zone.

*carefully puts the lid back on the can*

**Comment by madpilot** [comment]
Fixed 

![image](https://user-images.githubusercontent.com/19585/133005971-b7ea0a10-d166-4ef8-8ca4-535d42d3af31.png)
