### ISSUE TITLE
Price-related fields need units documented

### ISSUE THREAD

**Issue by GrahamLea** [amberelectric/public-api#69]
Looking at the API docs for `Usage`, it's clear that the `perKwh` field is in cents, but no unit is explicitly stated for `spotPerKwh` (I assume it's cents) or `cost` (🤷🏻‍♂️).

**Comment by madpilot** [comment]
It's the same (c/kWh).

I'll update the docs on Monday.

Thanks!

**Comment by madpilot** [comment]
Fixed

![image](https://user-images.githubusercontent.com/19585/133005958-88ede8bd-bf30-4cec-a25a-21abe487d11f.png)

**Comment by GrahamLea** [comment]
Ideally `cost` would have a unit too. Guessing it's cents.
