### ISSUE TITLE
TypeError: Origin https://app.amber.com.au is not allowed by Access-Control-Allow-Origin.

### ISSUE THREAD

**Issue by grahamtowle** [amberelectric/public-api#90]
I am using the developers page of the amber app and get the error code "TypeError: Origin https://app.amber.com.au is not allowed by Access-Control-Allow-Origin." when I try to get current prices. Can you please explain to me what the code means.
Thanks GT

**Comment by madpilot** [comment]
It is an unhelpful error message that says there is something wrong with your request.

What params are you passing in?

**Comment by grahamtowle** [comment]
API id which i just generated and the site ID from get sites. Left the rest as defaults.

**Comment by madpilot** [comment]
Which end point are you using?

**Comment by grahamtowle** [comment]
I copied the id from the sites and pasted it into the window for the current prices. I noticed that the site id is not fixed, it is different to the one I was getting the other day.

**Comment by madpilot** [comment]
The site id will only change if you have moved house. Let me see if I can find your account.

**Comment by madpilot** [comment]
Setting it up this way:

![image](https://user-images.githubusercontent.com/19585/148488615-04cbd0b9-67aa-4af8-8b57-bd31e9af4f69.png)

Should work. (Not that only the first part of your site ID is visible here - it should end in `MWQ`)

If not, let me know

**Comment by grahamtowle** [comment]
That is the site id I used the other day with mixed results. Today I started from scratch with a new token and got a site id ending in 990AM

**Comment by madpilot** [comment]
Can you post the complete output of the `/sites` call?

**Comment by grahamtowle** [comment]
[
  {
    "id": "01F5A5CRKMZ5BCX9P1S4V990AM",
    "nmi": "3052282872",
    "channels": [
      {
        "identifier": "E1",
        "type": "general"
      }
    ]
  }
]

**Comment by madpilot** [comment]
That's the example output. You need to hit execute first:

![image](https://user-images.githubusercontent.com/19585/148489525-5eded71f-3b04-4ade-b8ec-c48f4ee4597a.png)

**Comment by madpilot** [comment]
You should see a response box appear:

![image](https://user-images.githubusercontent.com/19585/148489606-d09a3b9f-cec5-4f7b-87cc-7fd7d7482085.png)

**Comment by madpilot** [comment]
(The UI package we use for this isn't great - I do this myself all the time)

**Comment by grahamtowle** [comment]
Sorry, it looks like i was using the example site id instead of mine. I assume I should stick to the latest token i generated.
Sorry again for wasting your time
Graham
[
  {
    "id": "01FNWQ03K00STR4TY601S9PMWQ",
    "nmi": "4103857035",
    "channels": [
      {
        "identifier": "E1",
        "type": "general"
      },
      {
        "identifier": "B1",
        "type": "feedIn"
      }
    ]
  }
]

**Comment by grahamtowle** [comment]
Thanks Again

**Comment by madpilot** [comment]
No worries! Happy to help
